apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-ds
  namespace: monitoring
  labels:
     grafana_datasource: "1"
data:
  datasource-pm.yaml: |
   apiVersion: 1
   datasources:
   - name: DEV_PROMETHEUS
     type: prometheus
     url: http://prometheus-server.monitoring.svc.cluster.local
     access: proxy
